In [1]:
# importing Numpy
import numpy as np

In [2]:
# creating arrays
arr1 = np.array([1,2,3,4])
arr2 = np.array([[1,2,], [3,4], [5,6]])


In [3]:
# Inspecting the arrays
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)

Array 1:
 [1 2 3 4]
Array 2:
 [[1 2]
 [3 4]
 [5 6]]


In [5]:
# Array properties
print("Shape of arr2:", arr2.shape)
print("Data type of arr2:", arr2.dtype)
print("Shape of arr1:", arr1.shape)
print("Data type of arr1:", arr1.dtype)

Shape of arr2: (3, 2)
Data type of arr2: int64
Shape of arr1: (4,)
Data type of arr1: int64


In [8]:
# Slicing and indexing
print("First element of arr1:", arr1[0])
print("Firstrow of arr2:\n", arr2[0, :])
print("All elements in second column of arr2:", arr2[:, 1])

First element of arr1: 1
Firstrow of arr2:
 [1 2]
All elements in second column of arr2: [2 4 6]


In [9]:
# Reshaping arrays
arr3 = np.arange(1, 13).reshape(3, 4)
print("Reshaped array:\n", arr3)

Reshaped array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
# performing mathematical operations
arr4 = np.array([1,2,3])
arr5 = np.array([4,5,6])
print("Element-wise addition:", arr4 + arr5)
print("Element-wise multiplication:", arr4 * arr5)

Element-wise addition: [5 7 9]
Element-wise multiplication: [ 4 10 18]


In [12]:
# Broadcasting
arr6 = np.array([1,2,3])
print("Broadcasting example:\n", arr6 + 5)

Broadcasting example:
 [6 7 8]


In [13]:
# Aggregate function
print("Sum of elements in arr6:", np.sum(arr6))
print("Mean of elements in arr6:", np.mean(arr6))
print("Max element in arr6:", np.max(arr6))

Sum of elements in arr6: 6
Mean of elements in arr6: 2.0
Max element in arr6: 3
