In [1]:
!pip install numpy

In [2]:
import numpy as np

#Creating Numpy arrays

In [3]:
# np.random.rand() allows yu to create rANDOM ARRAYS
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2)) # helps us create an arraay that is full of zeroes
full = np.full((2,2,2,), 7) # replacing all numbers in the array with the value 7
ones = np.ones((2,2,2)) # similar to zeroes array but replaces all the values with 1

In [4]:
data

array([[[0.32684091, 0.10708169, 0.28612445, 0.65890309],
        [0.47368562, 0.11758869, 0.06377045, 0.32932098],
        [0.27971892, 0.50355004, 0.84397033, 0.77391082]],

       [[0.90569369, 0.79694034, 0.57008231, 0.89099093],
        [0.00880586, 0.56300559, 0.59170129, 0.88024902],
        [0.90967139, 0.84552268, 0.92358513, 0.01330045]]])

In [5]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [6]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [7]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [8]:
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [9]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [10]:
type(arr)

numpy.ndarray

# Reading Numpy arrays

In [11]:
# Attributes
shape = data.shape
size = data.size
types = data.dtype

In [12]:
shape

(2, 3, 4)

In [13]:
size

24

In [14]:
types

dtype('float64')

In [15]:
# Slicing
arr = data[0]
slicer = data[0:2]
slicer2 = data[0][0:2]
reverse = data[-1]
singleval = data[0][0][0]

In [16]:
arr

array([[0.32684091, 0.10708169, 0.28612445, 0.65890309],
       [0.47368562, 0.11758869, 0.06377045, 0.32932098],
       [0.27971892, 0.50355004, 0.84397033, 0.77391082]])

In [17]:
slicer

array([[[0.32684091, 0.10708169, 0.28612445, 0.65890309],
        [0.47368562, 0.11758869, 0.06377045, 0.32932098],
        [0.27971892, 0.50355004, 0.84397033, 0.77391082]],

       [[0.90569369, 0.79694034, 0.57008231, 0.89099093],
        [0.00880586, 0.56300559, 0.59170129, 0.88024902],
        [0.90967139, 0.84552268, 0.92358513, 0.01330045]]])

In [18]:
slicer2

array([[0.32684091, 0.10708169, 0.28612445, 0.65890309],
       [0.47368562, 0.11758869, 0.06377045, 0.32932098]])

In [19]:
reverse

array([[0.90569369, 0.79694034, 0.57008231, 0.89099093],
       [0.00880586, 0.56300559, 0.59170129, 0.88024902],
       [0.90967139, 0.84552268, 0.92358513, 0.01330045]])

In [20]:
singleval

np.float64(0.3268409118308373)

# Updating Numpy arrays

In [21]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [22]:
list1

array([0.06404909, 0.82598116, 0.26156008, 0.98300566, 0.16848212,
       0.21603902, 0.62469113, 0.52191125, 0.44381054, 0.18648918])

In [23]:
list2

array([0.52146917, 0.5735535 , 0.310748  , 0.67739934, 0.12027432,
       0.61777596, 0.66880587, 0.88459768, 0.15180488, 0.52728826])

In [24]:
# Basic Maths
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2) # for dot products

In [25]:
add

array([0.58551826, 1.39953466, 0.57230808, 1.660405  , 0.28875644,
       0.83381499, 1.29349699, 1.40650893, 0.59561542, 0.71377744])

In [26]:
sub

array([-0.45742009,  0.25242766, -0.04918792,  0.30560632,  0.04820779,
       -0.40173694, -0.04411474, -0.36268644,  0.29200566, -0.34079909])

In [27]:
div


array([0.1228243 , 1.44011178, 0.84171122, 1.45114648, 1.40081533,
       0.34970448, 0.93403955, 0.58999843, 2.92355907, 0.35367595])

In [28]:
mult

array([0.03339962, 0.47374439, 0.08127927, 0.66588738, 0.02026407,
       0.13346372, 0.41779709, 0.46168148, 0.06737261, 0.09833355])

In [29]:
# The dot product is computed by multiplying corresponding elements of the two lists and then summing those products. For example, if list1 = [a, b, c] and list2 = [x, y, z], the dot product would be calculated as a*x + b*y + c*z.
dot

np.float64(2.4532231854522966)

In [30]:
# Statistical functions in Numpy [SAP LEMM]

sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2, 7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)



In [31]:
sqrt

np.float64(5.0)

In [32]:
ab

np.int64(2)

In [33]:
power

np.int64(128)

In [34]:
log

np.float64(3.2188758248682006)

In [35]:
exp

array([ 7.3890561 , 20.08553692])

In [36]:
mins

np.float64(0.06404908579380153)

In [37]:
maxs

np.float64(0.9830056613881617)

In [38]:
# to update a value within an array
data[0][0][0] = 700

In [39]:
data

array([[[7.00000000e+02, 1.07081694e-01, 2.86124454e-01, 6.58903086e-01],
        [4.73685619e-01, 1.17588690e-01, 6.37704528e-02, 3.29320981e-01],
        [2.79718924e-01, 5.03550038e-01, 8.43970335e-01, 7.73910818e-01]],

       [[9.05693688e-01, 7.96940341e-01, 5.70082307e-01, 8.90990934e-01],
        [8.80585610e-03, 5.63005590e-01, 5.91701290e-01, 8.80249020e-01],
        [9.09671385e-01, 8.45522679e-01, 9.23585128e-01, 1.33004502e-02]]])

In [40]:
# To sort our data
data.sort()
data

array([[[1.07081694e-01, 2.86124454e-01, 6.58903086e-01, 7.00000000e+02],
        [6.37704528e-02, 1.17588690e-01, 3.29320981e-01, 4.73685619e-01],
        [2.79718924e-01, 5.03550038e-01, 7.73910818e-01, 8.43970335e-01]],

       [[5.70082307e-01, 7.96940341e-01, 8.90990934e-01, 9.05693688e-01],
        [8.80585610e-03, 5.63005590e-01, 5.91701290e-01, 8.80249020e-01],
        [1.33004502e-02, 8.45522679e-01, 9.09671385e-01, 9.23585128e-01]]])

In [41]:
# to reshape your array
print(data.shape)

(2, 3, 4)


In [42]:
data = data.reshape((2,2,-1))
data.shape

(2, 2, 6)

In [43]:
# Appending or inserting values to the end of an array
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [44]:
# To insert in a specific area
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


# Deleting Numpy arrays

In [45]:
data

array([[[1.07081694e-01, 2.86124454e-01, 6.58903086e-01, 7.00000000e+02,
         6.37704528e-02, 1.17588690e-01],
        [3.29320981e-01, 4.73685619e-01, 2.79718924e-01, 5.03550038e-01,
         7.73910818e-01, 8.43970335e-01]],

       [[5.70082307e-01, 7.96940341e-01, 8.90990934e-01, 9.05693688e-01,
         8.80585610e-03, 5.63005590e-01],
        [5.91701290e-01, 8.80249020e-01, 1.33004502e-02, 8.45522679e-01,
         9.09671385e-01, 9.23585128e-01]]])

In [46]:
# to delete the first array within each one of these two arrays in the data array. Axis 1 is to specify we are deleting a row, not a column
np.delete(data, 0,axis=1)

array([[[0.32932098, 0.47368562, 0.27971892, 0.50355004, 0.77391082,
         0.84397033]],

       [[0.59170129, 0.88024902, 0.01330045, 0.84552268, 0.90967139,
         0.92358513]]])

# Exporting Numpy arrays

In [49]:
# to save / export an array
np.save("new array", data)

In [50]:
# to reload that array
test = np.load("new array.npy")