In [2]:
!pip install numpy

In [3]:
import numpy as np

#Creating Numpy arrays

In [4]:
# np.random.rand() allows yu to create rANDOM ARRAYS
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2)) # helps us create an arraay that is full of zeroes
full = np.full((2,2,2,), 7) # replacing all numbers in the array with the value 7
ones = np.ones((2,2,2)) # similar to zeroes array but replaces all the values with 1

In [5]:
data

array([[[0.59582123, 0.75541044, 0.46827084, 0.5102118 ],
        [0.97016403, 0.59674891, 0.12890209, 0.03727373],
        [0.97517495, 0.77414566, 0.56111136, 0.72714966]],

       [[0.1172538 , 0.57435591, 0.9688604 , 0.08225067],
        [0.90497178, 0.5454385 , 0.88665463, 0.57243727],
        [0.9677039 , 0.59191019, 0.08700935, 0.81741015]]])

In [6]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [7]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [8]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [9]:
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [10]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [11]:
type(arr)

numpy.ndarray

# Reading Numpy arrays

In [12]:
# Attributes
shape = data.shape
size = data.size
types = data.dtype

In [13]:
shape

(2, 3, 4)

In [14]:
size

24

In [16]:
types

dtype('float64')

In [22]:
# Slicing
arr = data[0]
slicer = data[0:2]
slicer2 = data[0][0:2]
reverse = data[-1]
singleval = data[0][0][0]

In [18]:
arr

array([[0.59582123, 0.75541044, 0.46827084, 0.5102118 ],
       [0.97016403, 0.59674891, 0.12890209, 0.03727373],
       [0.97517495, 0.77414566, 0.56111136, 0.72714966]])

In [19]:
slicer

array([[[0.59582123, 0.75541044, 0.46827084, 0.5102118 ],
        [0.97016403, 0.59674891, 0.12890209, 0.03727373],
        [0.97517495, 0.77414566, 0.56111136, 0.72714966]],

       [[0.1172538 , 0.57435591, 0.9688604 , 0.08225067],
        [0.90497178, 0.5454385 , 0.88665463, 0.57243727],
        [0.9677039 , 0.59191019, 0.08700935, 0.81741015]]])

In [23]:
slicer2

array([[0.59582123, 0.75541044, 0.46827084, 0.5102118 ],
       [0.97016403, 0.59674891, 0.12890209, 0.03727373]])

In [20]:
reverse

array([[0.1172538 , 0.57435591, 0.9688604 , 0.08225067],
       [0.90497178, 0.5454385 , 0.88665463, 0.57243727],
       [0.9677039 , 0.59191019, 0.08700935, 0.81741015]])

In [21]:
singleval

0.5958212280598009

# Updating Numpy arrays

In [24]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [25]:
list1

array([0.29495088, 0.77512916, 0.71674268, 0.25203897, 0.87541446,
       0.20637117, 0.6123172 , 0.11900169, 0.94771527, 0.97502091])

In [26]:
list2

array([0.19650716, 0.75983275, 0.29354191, 0.6172462 , 0.75121976,
       0.78088498, 0.67338493, 0.93399336, 0.46600494, 0.79260579])

In [28]:
# Basic Maths
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2) # for dot products

In [29]:
add

array([0.49145805, 1.53496191, 1.01028459, 0.86928516, 1.62663422,
       0.98725615, 1.28570213, 1.05299505, 1.41372021, 1.7676267 ])

In [30]:
sub

array([ 0.09844372,  0.01529641,  0.42320077, -0.36520723,  0.1241947 ,
       -0.57451381, -0.06106773, -0.81499167,  0.48171032,  0.18241511])

In [32]:
div


array([1.5009676 , 1.02013128, 2.44170475, 0.4083281 , 1.16532406,
       0.26427858, 0.9093123 , 0.12741171, 2.03370218, 1.23014607])

In [33]:
mult

array([0.05795996, 0.58896852, 0.21039401, 0.15557009, 0.65762864,
       0.16115215, 0.41232518, 0.11114679, 0.44164   , 0.77280722])

In [35]:
# The dot product is computed by multiplying corresponding elements of the two lists and then summing those products. For example, if list1 = [a, b, c] and list2 = [x, y, z], the dot product would be calculated as a*x + b*y + c*z.
dot

3.5695925617768793

In [37]:
# Statistical functions in Numpy [SAP LEMM]

sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2, 7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)



In [38]:
sqrt

5.0

In [39]:
ab

2

In [40]:
power

128

In [41]:
log

3.2188758248682006

In [43]:
exp

array([ 7.3890561 , 20.08553692])

In [44]:
mins

0.11900168794128729

In [45]:
maxs

0.9750209051564505

In [47]:
# to update a value within an array
data[0][0][0] = 700

In [48]:
data

array([[[7.00000000e+02, 7.55410439e-01, 4.68270839e-01, 5.10211799e-01],
        [9.70164028e-01, 5.96748913e-01, 1.28902087e-01, 3.72737338e-02],
        [9.75174952e-01, 7.74145664e-01, 5.61111358e-01, 7.27149662e-01]],

       [[1.17253804e-01, 5.74355911e-01, 9.68860396e-01, 8.22506656e-02],
        [9.04971781e-01, 5.45438500e-01, 8.86654634e-01, 5.72437269e-01],
        [9.67703899e-01, 5.91910192e-01, 8.70093475e-02, 8.17410151e-01]]])

In [49]:
# To sort our data
data.sort()
data

array([[[4.68270839e-01, 5.10211799e-01, 7.55410439e-01, 7.00000000e+02],
        [3.72737338e-02, 1.28902087e-01, 5.96748913e-01, 9.70164028e-01],
        [5.61111358e-01, 7.27149662e-01, 7.74145664e-01, 9.75174952e-01]],

       [[8.22506656e-02, 1.17253804e-01, 5.74355911e-01, 9.68860396e-01],
        [5.45438500e-01, 5.72437269e-01, 8.86654634e-01, 9.04971781e-01],
        [8.70093475e-02, 5.91910192e-01, 8.17410151e-01, 9.67703899e-01]]])

In [50]:
# to reshape your array
print(data.shape)

(2, 3, 4)


In [51]:
data = data.reshape((2,2,-1))
data.shape

(2, 2, 6)

In [53]:
# Appending or inserting values to the end of an array
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [54]:
# To insert in a specific area
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


# Deleting Numpy arrays

In [55]:
data

array([[[4.68270839e-01, 5.10211799e-01, 7.55410439e-01, 7.00000000e+02,
         3.72737338e-02, 1.28902087e-01],
        [5.96748913e-01, 9.70164028e-01, 5.61111358e-01, 7.27149662e-01,
         7.74145664e-01, 9.75174952e-01]],

       [[8.22506656e-02, 1.17253804e-01, 5.74355911e-01, 9.68860396e-01,
         5.45438500e-01, 5.72437269e-01],
        [8.86654634e-01, 9.04971781e-01, 8.70093475e-02, 5.91910192e-01,
         8.17410151e-01, 9.67703899e-01]]])

In [56]:
# to delete the first array within each one of these two arrays in the data array. Axis 1 is to specify we are deleting a row, not a column
np.delete(data, 0,axis=1)

array([[[0.59674891, 0.97016403, 0.56111136, 0.72714966, 0.77414566,
         0.97517495]],

       [[0.88665463, 0.90497178, 0.08700935, 0.59191019, 0.81741015,
         0.9677039 ]]])

# Exporting Numpy arrays

In [57]:
# to save / export an array
np.save("new array", data)

In [ ]:
# to reload that array
test = np.load("new array.npy")